
services:
  oauth-relay:
    build: 
      context: ./oauth-relay
      dockerfile: Dockerfile
    container_name: waybar-oauth-relay
    ports:
      - "8181:8080"
    environment:
      - PORT=8080
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REDIRECT_URI=http://localhost:8181/auth/callback
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/oauth-relay", "-health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - waybar-network

networks:
  waybar-network:
    driver: bridge